# Generated by Django 4.2.9 on 2024-02-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время загрузки')),
                ('processed', models.BooleanField(default=False, verbose_name='статус выполнения')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
